apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mzaa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jmdi-tenant/rhtap-demo-app/hacbs-test-project-mzaa@sha256:7964f7ad4dc17d26491b8935f7e32647dd2110e51ab915309cf6b4fc5a5b14ce
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
