apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mzaa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jmdi-tenant/rhtap-demo-app/hacbs-test-project-mzaa@sha256:9a2db3d42245df1be1acd3f0e7d60bcda9fcd4088df696e5b1a0156a26b7795b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
