apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mzaa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jmdi-tenant/rhtap-demo-app/hacbs-test-project-mzaa@sha256:a687c3fa485b74769cdf8fabc654893e263625160334360003f670925dd4f195
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
